os:
- linux
- osx
language: rust
rust:
- stable
- beta
- nightly
before_script:
- |
  if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    brew update
    brew install --force openssl
    export OPENSSL_DIR=/usr/local/opt/openssl
    export OPENSSL_ROOT_DIR=$OPENSSL_DIR
  else
    curl -sSL https://cmake.org/files/v3.5/cmake-3.5.2-Linux-x86_64.tar.gz | sudo tar -xzC $PWD
    export PATH=$PWD/cmake-3.5.2-Linux-x86_64/bin/:$PATH
  fi
script:
- make test
- cargo doc

