language: rust
rust:
- stable
- beta
- nightly
addons:
  apt:
    sources:
    - sourceline: 'ppa:george-edison55/cmake-3.x'
before_script:
- apt-get update
- apt-get upgrade cmake
script:
- cargo test
- cargo doc

