name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: Swatinem/rust-cache@v2
    - name: tests
      run: make test
    - name: docs
      run: cargo doc
    - name: usage as dependency
      run: |
          cargo init user
          cd user
          cargo add --path ..
          cargo check
           

